build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # Tergolong kritis
    complexity: 2
    LongMethod: 1
    LargeClass: 1

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 100
    ignoreAnnotated: ['Composable']
  LargeClass:
    active: true
    threshold: 150
  TooManyFunctions:
    active: true
    thresholdInFiles: 10
    thresholdInClasses: 10
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 10
  NestedBlockDepth:
    active: true
    threshold: 3

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2', '5000', '0xFF0A2A5E', '0xFFD62839', '0xFFF4F6F9', '0.9f', '0.95f']
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    active: true
  UnusedImports:
    active: true

exceptions:
  active: true
  SwallowedException:
    active: true
  TooGenericExceptionCaught:
    active: true
