build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # Tergolong kritis
    complexity: 2
    LongMethod: 1
    LargeClass: 1

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 30
  LargeClass:
    active: true
    threshold: 150
  TooManyFunctions:
    active: true
    thresholdInFiles: 10
    thresholdInClasses: 10
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 10
  NestedBlockDepth:
    active: true
    threshold: 3

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
  UnusedPrivateMember:
    active: true
  UnusedImports:
    active: true

exceptions:
  active: true
  SwallowedException:
    active: true
  TooGenericExceptionCaught:
    active: true
